from __future__ import annotations
import io
from datetime import datetime
from typing import Any

from docx import Document
from docx.shared import Pt, RGBColor


def generate_docx(
    job: Any,
    doc: Any,
    segments: list[Any],
) -> bytes:
    document = Document()

    # Title
    title_para = document.add_heading(job.title or "Transcript", 0)
    title_para.runs[0].font.color.rgb = RGBColor(0x1B, 0x2A, 0x4A)

    # Metadata block
    meta = document.add_paragraph()
    _bold_kv(meta, "Source", job.source_url)
    _bold_kv(meta, "\nType", job.source_type.title())
    if job.duration_seconds:
        _bold_kv(meta, "\nDuration", _fmt_duration(job.duration_seconds))
    if job.language:
        _bold_kv(meta, "\nLanguage", job.language.upper())
    strategy = job.processing_strategy
    strategy_str = strategy.value if hasattr(strategy, "value") else str(strategy)
    _bold_kv(meta, "\nProcessing", strategy_str.title())
    if job.completed_at:
        _bold_kv(meta, "\nTranscribed", job.completed_at.strftime("%Y-%m-%d %H:%M UTC"))

    # Confidence summary (if available)
    avg_conf = getattr(doc, "average_confidence", None)
    low_count = getattr(doc, "low_confidence_count", 0) or 0
    if avg_conf is not None:
        pct = int(float(avg_conf) * 100)
        _bold_kv(meta, "\nAvg. confidence", f"{pct}%")
        if low_count:
            _bold_kv(meta, "\nLow-confidence segments", str(low_count))

    # Accuracy disclaimer
    if low_count > 0:
        disclaimer = document.add_paragraph(
            "Note: This transcript contains segments with low confidence scores. "
            "Some words may be inaccurate — please review carefully."
        )
        disclaimer.runs[0].font.color.rgb = RGBColor(0xB4, 0x5A, 0x00)
        disclaimer.runs[0].font.italic = True
        disclaimer.runs[0].font.size = Pt(9)
    elif avg_conf is None:
        disclaimer = document.add_paragraph(
            "Note: No confidence data is available for this transcript."
        )
        disclaimer.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
        disclaimer.runs[0].font.italic = True
        disclaimer.runs[0].font.size = Pt(9)

    # Full text section
    document.add_heading("Full Transcript", level=1)
    document.add_paragraph(doc.full_text)

    # Timestamped segments table
    if segments:
        document.add_heading("Timestamped Segments", level=1)
        table = document.add_table(rows=1, cols=3)
        table.style = "Light List Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Start"
        hdr[1].text = "End"
        hdr[2].text = "Text"

        for seg in segments:
            text = seg.text.strip()
            if not text:
                continue
            row = table.add_row().cells
            row[0].text = _fmt_ts(float(seg.start_seconds))
            row[1].text = _fmt_ts(float(seg.end_seconds))
            row[2].text = text

    # Footer
    document.add_paragraph()
    footer = document.add_paragraph(
        "Generated by Bayyn — Store knowledge, not media. "
        f"Exported {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(0x9A, 0x9A, 0x9A)

    buf = io.BytesIO()
    document.save(buf)
    return buf.getvalue()


def _bold_kv(para: Any, key: str, value: str) -> None:
    run = para.add_run(key + ": ")
    run.bold = True
    para.add_run(value)


def _fmt_duration(seconds: int) -> str:
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    if h:
        return f"{h}h {m}m {s}s"
    return f"{m}m {s}s"


def _fmt_ts(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"
