from __future__ import annotations
import io
from datetime import datetime
from typing import TYPE_CHECKING, Any

from docx import Document
from docx.shared import Pt, RGBColor

if TYPE_CHECKING:
    from app.models.transcript_document import TranscriptDocument
    from app.models.transcript_segment import TranscriptSegment
    from app.models.transcription_job import TranscriptionJob


def generate_docx(
    job: Any,
    doc: Any,
    segments: list[Any],
) -> bytes:
    document = Document()

    title = document.add_heading(job.title or "Transcript", 0)
    title.runs[0].font.color.rgb = RGBColor(0x1B, 0x2A, 0x4A)

    meta = document.add_paragraph()
    meta.add_run("Source: ").bold = True
    meta.add_run(job.source_url)
    meta.add_run("\nType: ").bold = True
    meta.add_run(job.source_type.title())
    if job.duration_seconds:
        meta.add_run("\nDuration: ").bold = True
        meta.add_run(_format_duration(job.duration_seconds))
    if job.language:
        meta.add_run("\nLanguage: ").bold = True
        meta.add_run(job.language)
    meta.add_run("\nProcessing: ").bold = True
    strategy = job.processing_strategy
    strategy_str = strategy.value if hasattr(strategy, "value") else str(strategy)
    meta.add_run(strategy_str.title())
    if job.completed_at:
        meta.add_run("\nTranscribed: ").bold = True
        meta.add_run(job.completed_at.strftime("%Y-%m-%d %H:%M UTC"))

    document.add_heading("Full Transcript", level=1)
    document.add_paragraph(doc.full_text)

    if segments:
        document.add_heading("Timestamped Segments", level=1)
        table = document.add_table(rows=1, cols=3)
        table.style = "Light List Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Start"
        hdr[1].text = "End"
        hdr[2].text = "Text"

        for seg in segments:
            row = table.add_row().cells
            row[0].text = _format_ts(float(seg.start_seconds))
            row[1].text = _format_ts(float(seg.end_seconds))
            row[2].text = seg.text.strip()

    document.add_paragraph()
    footer = document.add_paragraph(
        "Generated by Bayyn — Store knowledge, not media. "
        f"Exported {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(0x9A, 0x9A, 0x9A)

    buf = io.BytesIO()
    document.save(buf)
    return buf.getvalue()


def _format_duration(seconds: int) -> str:
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    if h:
        return f"{h}h {m}m {s}s"
    return f"{m}m {s}s"


def _format_ts(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"
